const {Router} = require("express")
const { registerUser, loginUser } = require("../controllers/user.contoller")
const { registerTask, getAllTasks, updateTask, deleteTask } = require("../controllers/task.controller")
const auth = require("../middlewares/auth")
const { registerSubTask, getAllSubTasks } = require("../controllers/subtask.controller")
const userRouter = Router()
userRouter.post("/signup",registerUser)
userRouter.post("/login",loginUser)
userRouter.post("/tasks",auth,registerTask)
userRouter.post("/all",auth,getAllTasks)
userRouter.patch("/update/:id",auth,updateTask)
userRouter.delete("/delete/:id",auth,deleteTask)
userRouter.post("/subtasks",auth,registerSubTask)
userRouter.get("/getalltasks",auth,getAllSubTasks)
module.exports = userRouter 